### ISSUE TITLE
Handle 404 pages

### ISSUE THREAD

**Issue by HoverBaum** [graforlock/choo-bandwagon#2]
Do we want to provide a route for the 404?

I think it would be nice to have a 404 page provided by default. Seems that is a general thing people might expect and other starter-kits like choo-create-app provide this.

**Comment by graforlock** [comment]
Yeah, there is no handling provided by default, although it may be a bit more tricky in isomorphic apps (depending what people want). The template definitely needs a bit more stuff and functionality out-of-the-box.

**Comment by graforlock** [comment]
Just added a 404 route handler in `0.0.3` as a patch.
